// File Name:	BODYFACT.D
// Purpose:	Data file for Conversion factors and references 
// Last UpDate:	16.Oct.97
// NOTE:-	
//	Variable declarations are in BODYVBLS.D

nEOSCirFac = 0.9;	
nWaistCirFac = 0.9; 
nBreastCirFac = 0.9;
nChestCirFac = 0.9;
nSCirFac = 2.5;
nNeckFac_1 = 0.9;
nNeckFac_2 = 6;
nNeckFac_3 = 0.125;
nNeckFac_4 = 1.3;
nNeckFac_5 = 1.3;
nChildUpperAge = 6;
nBackNeckScoopFacChild = 0.375 ;
nBackNeckScoopFacAdult = 0.75 ;
nHighSLineFac = 0.5;
nRegAxillaFac_2 = 0.75;
nRegAxillaNormal = 2 ;
nRegAxillaLargeAdult = 2.5;
nRegAxillaChild = 1.5;
nInsertToNeckMinDist = 0.625 ;
nNeckFrontFac = 1;
nBraFac_1 = 0.25 + 0.5 ;				// 1/4" left of axilla shoulder line //NB mods  15.Oct.97
nBraFac_SleeveLess = 0.75 +0.5 ;		// 3/4" left of axilla shoulder line //NB mods  15.Oct.97
nBraMinEOS = 1.5 ;
nBraMinProfile = 0.5; 
nBraPosFacX = 1.39;			// Scaling offset to top of bra disk
nBraPosFacY= 1.75 ;
sLtHandColor = "blue";
sRtHandColor = "red";
nSeamAllowance = 0.125;
nBackNeckRadius = 10;
nZipFac = 0.95;
nMeshAxillaGussetFac = 0.75 ;
nMSLengthGusset = 2.1875;
nMeshAxillaGussetBoysFac =  0.8125 ;
nMSLengthGussetBoys = 2.375;

bPrevAxillaWasMesh = %false;