//DRAFIX Macro created - 05-21-2018  01:05:51
//Patient    - test, 3,
//Work Order - 23
//by Visual Basic
STRING sName, sFileNo, sPatient, sAge, sUnits, sSex, sWorkOrder, sTemplateEngineer, sOrderDate;
STRING sCADFile, sDiagnosis;
sCADFile= "C:\\IMAGABLE\\Jobskin Sample 2  J31332.CAD.DWG";
sFileNo = "3";
sPatient = "test";
sAge = "3";
sUnits ="cm";
sSex = "Male";
sDiagnosis ="Assist fluid dynamics";
sWorkOrder ="23";
sOrderDate ="21/05/2018";
sTemplateEngineer ="Kathy Cook";
@C:\JOBST3xx\CADLINK\CL_UPDTE.D;
